CREATE DATABASE IF NOT EXISTS hockey_data_hub;

USE hockey_data_hub;

CREATE TABLE IF NOT EXISTS `games` (
  `id` int unsigned NOT NULL,
  `season` int NOT NULL,
  `type` varchar(45) NOT NULL,
  `dateTime` varchar(255) NOT NULL,
  `lastPeriod` varchar(45) NOT NULL,
  `status` varchar(45) NOT NULL,
  `venue` varchar(255) DEFAULT NULL,
  `playoffRound` varchar(255) DEFAULT NULL,
  `playoffSeriesId` int DEFAULT NULL,
  `playoffGameNumber` varchar(45) DEFAULT NULL,
  `awayId` int NOT NULL,
  `awayName` varchar(45) NOT NULL,
  `awayShortName` varchar(45) DEFAULT NULL,
  `awayAbbreviation` varchar(45) NOT NULL,
  `awayLogoURL` mediumtext NOT NULL,
  `awayGoals` int NOT NULL,
  `awayGoalScorers` mediumtext NOT NULL,
  `homeId` int NOT NULL,
  `homeName` varchar(45) NOT NULL,
  `homeShortName` varchar(45) DEFAULT NULL,
  `homeAbbreviation` varchar(45) NOT NULL,
  `homeLogoURL` mediumtext NOT NULL,
  `homeGoals` int NOT NULL,
  `homeGoalScorers` mediumtext NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ID_UNIQUE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `goalies` (
  `id` bigint NOT NULL,
  `playerId` int NOT NULL,
  `player` varchar(255) DEFAULT NULL,
  `teamId` int NOT NULL,
  `team` varchar(45) DEFAULT NULL,
  `teamShortName` varchar(45) DEFAULT NULL,
  `teamAbbreviation` varchar(45) DEFAULT NULL,
  `season` int DEFAULT NULL,
  `imageURL` mediumtext,
  `teamLogoURL` mediumtext,
  `number` varchar(45) DEFAULT NULL,
  `captain` tinyint DEFAULT NULL,
  `alternateCaptain` tinyint DEFAULT NULL,
  `catches` varchar(45) DEFAULT NULL,
  `nationality` varchar(45) DEFAULT NULL,
  `dateOfBirth` varchar(45) DEFAULT NULL,
  `placeOfBirth` varchar(255) DEFAULT NULL,
  `height` varchar(45) DEFAULT NULL,
  `weight` int DEFAULT NULL,
  `gamesPlayed` int DEFAULT NULL,
  `gamesStarted` int DEFAULT NULL,
  `wins` int DEFAULT NULL,
  `shotsAgainst` int DEFAULT NULL,
  `goalsAgainst` int DEFAULT NULL,
  `saves` int DEFAULT NULL,
  `savePercentage` float DEFAULT NULL,
  `goalsAgainstAverage` float DEFAULT NULL,
  `shutouts` int DEFAULT NULL,
  `timeOnIce` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ID_UNIQUE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `playoff_series` (
  `id` int NOT NULL,
  `season` int NOT NULL,
  `roundId` int DEFAULT NULL,
  `round` varchar(45) DEFAULT NULL,
  `seriesId` int DEFAULT NULL,
  `team1Id` int NOT NULL,
  `team1Name` varchar(45) DEFAULT NULL,
  `team1ShortName` varchar(45) DEFAULT NULL,
  `team1Abbreviation` varchar(45) DEFAULT NULL,
  `team1LogoURL` mediumtext,
  `team2Id` int NOT NULL,
  `team2Name` varchar(45) DEFAULT NULL,
  `team2ShortName` varchar(45) DEFAULT NULL,
  `team2Abbreviation` varchar(45) DEFAULT NULL,
  `team2LogoURL` mediumtext,
  `status` varchar(45) DEFAULT NULL,
  `statusShort` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ID_UNIQUE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `seasons` (
  `id` int NOT NULL,
  `regularSeasonStartDate` varchar(255) DEFAULT NULL,
  `regularSeasonEndDate` varchar(255) DEFAULT NULL,
  `seasonEndDate` varchar(255) DEFAULT NULL,
  `numberOfGames` int DEFAULT NULL,
  `conferencesInUse` tinyint DEFAULT NULL,
  `divisionsInUse` tinyint DEFAULT NULL,
  `wildCardInUse` tinyint DEFAULT NULL,
  `conferences` mediumtext,
  `divisions` mediumtext,
  `playoffRounds` mediumtext,
  `tiesInUse` tinyint DEFAULT NULL,
  `overtimeLossPointInUse` tinyint DEFAULT NULL,
  `powerPlayStatsTracked` tinyint DEFAULT NULL,
  `shootingStatsTracked` tinyint DEFAULT NULL,
  `faceoffStatsTracked` tinyint DEFAULT NULL,
  `saveStatsTracked` tinyint DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ID_UNIQUE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `skaters` (
  `id` bigint NOT NULL,
  `playerId` int NOT NULL,
  `player` varchar(255) DEFAULT NULL,
  `teamId` int NOT NULL,
  `team` varchar(45) DEFAULT NULL,
  `teamShortName` varchar(45) DEFAULT NULL,
  `teamAbbreviation` varchar(45) DEFAULT NULL,
  `season` int DEFAULT NULL,
  `imageURL` mediumtext,
  `teamLogoURL` mediumtext,
  `number` varchar(45) DEFAULT NULL,
  `position` varchar(45) DEFAULT NULL,
  `positionType` varchar(45) DEFAULT NULL,
  `captain` tinyint DEFAULT NULL,
  `alternateCaptain` tinyint DEFAULT NULL,
  `shoots` varchar(45) DEFAULT NULL,
  `nationality` varchar(45) DEFAULT NULL,
  `dateOfBirth` varchar(45) DEFAULT NULL,
  `placeOfBirth` varchar(255) DEFAULT NULL,
  `height` varchar(45) DEFAULT NULL,
  `weight` int DEFAULT NULL,
  `gamesPlayed` int DEFAULT NULL,
  `goals` int DEFAULT NULL,
  `assists` int DEFAULT NULL,
  `points` int DEFAULT NULL,
  `pointsPerGamesPlayed` varchar(45) DEFAULT NULL,
  `powerPlayGoals` int DEFAULT NULL,
  `powerPlayPoints` int DEFAULT NULL,
  `shots` int DEFAULT NULL,
  `shootingPercentage` float DEFAULT NULL,
  `faceoffPercentage` float DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ID_UNIQUE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `standings` (
  `id` int NOT NULL,
  `teamId` int NOT NULL,
  `team` varchar(45) DEFAULT NULL,
  `teamShortName` varchar(45) DEFAULT NULL,
  `teamAbbreviation` varchar(45) DEFAULT NULL,
  `season` int DEFAULT NULL,
  `logoURL` mediumtext,
  `conference` varchar(45) DEFAULT NULL,
  `division` varchar(45) DEFAULT NULL,
  `clinchIndicator` varchar(45) DEFAULT NULL,
  `divisionRank` int DEFAULT NULL,
  `leagueRank` int DEFAULT NULL,
  `points` int DEFAULT NULL,
  `gamesPlayed` int DEFAULT NULL,
  `wins` int DEFAULT NULL,
  `losses` int DEFAULT NULL,
  `ties` int DEFAULT NULL,
  `overtimeLosses` int DEFAULT NULL,
  `goalsFor` int DEFAULT NULL,
  `goalsAgainst` int DEFAULT NULL,
  `difference` int DEFAULT NULL,
  `homeRecord` varchar(45) DEFAULT NULL,
  `awayRecord` varchar(45) DEFAULT NULL,
  `last10` varchar(45) DEFAULT NULL,
  `streak` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ID_UNIQUE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `teams` (
  `id` int NOT NULL,
  `name` varchar(45) NOT NULL,
  `locationName` varchar(45) DEFAULT NULL,
  `teamName` varchar(45) DEFAULT NULL,
  `abbreviation` varchar(45) DEFAULT NULL,
  `lightLogoURL` mediumtext,
  `venueName` varchar(45) DEFAULT NULL,
  `venueCity` varchar(45) DEFAULT NULL,
  `firstYearOfPlay` int DEFAULT NULL,
  `conference` varchar(45) DEFAULT NULL,
  `division` varchar(45) DEFAULT NULL,
  `backgroundColour` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ID_UNIQUE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;